### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by RajabMuhammad** [PacktPublishing/Building-Recommendation-Systems-with-Python#34]
Hello, @ericandrer sections 2, 3, and 4 are missing movies.csv, links.csv, ratings.csv, tags.csv datasets. can you please attach them too? 
Thank you so much.

**Comment by ericandrer** [comment]
Hi @RajabMuhammad this is a duplicate issue #5  Please find all the necessary files to complete this course on [G Drive](https://drive.google.com/drive/folders/13sgsgTDV_XmtZnAI1xcdLEAVzLUeVcZ7?usp=sharing) there weren't uploaded on Github due to size restrictions. [Learn more](https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota)
